version: 2
updates:
  - package-ecosystem: "maven"
    # Files stored in repository root
    directory: "/web-server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
